[package]
name = "x-dbsp"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
x-common = { workspace = true }
