//! Space: a repository at a specific location.
//!
//! Conceptually a [`Space`] is a repository, the persistent home for a
//! single subject DID. A user's "profile" is itself just a space that
//! plays a distinguished role (it owns the identity that creates and
//! delegates other spaces). Anything you can do to a space, you can do
//! to a profile: open it, store blobs, publish cells, save credentials,
//! retain certificates.
//!
//! A space groups the four storage concerns the runtime needs: archive
//! (content-addressed blobs), memory (cells / mutable state), credentials
//! (keys + secrets), and certificates (delegations). At the capability
//! layer they appear as a single provider that dispatches each effect to
//! the correct field.
//!
//! Each field is independently typed. In a typical native deployment all
//! four fields are backed by the same `FileSystem` provider, but nothing
//! requires that — on the web you might want archive on OPFS for large
//! blob throughput, memory on IndexedDB for transactional cells, and
//! credentials on the platform's native key store. [`Space`] makes those
//! mix-and-match decisions explicit at the type level.
//!
//! [`SpaceProvider`] is a trait alias summarizing the full set of
//! `Provider<E>` impls a mounted space must satisfy. The dispatch wiring
//! for archive / memory / credential is generated by
//! `#[derive(Provider)]`; the access effects ([`Prove`] and
//! [`AccessRetain`]) are forwarded by hand because their generic bounds
//! depend on the protocol's associated types.
//!
//! At runtime [`Storage`] holds a mapping from `did:key` to the
//! corresponding [`Space`], so the composition is invisible to consumers:
//! capabilities address a subject DID and the runtime routes each effect
//! to the right backend. Consumers stay in capability-land — the space's
//! DID is the root of any capability chain — and never have to reason
//! about which underlying provider serves which effect.
//!
//! [`Storage`]: super::Storage
//!
//! `Resource<Location>` is implemented so a `Space` can be opened from a
//! single [`Location`] — each field opens from the same location, which is
//! how higher-level runtimes (`Storage`) can construct mounted spaces
//! without knowing the concrete provider types.

use dialog_capability::access::{AuthorizeError, Protocol, Prove, Retain as AccessRetain};
use dialog_capability::{Capability, Provider};
use dialog_common::{ConditionalSend, ConditionalSync};
use dialog_credentials::Credential;
use dialog_effects::credential::Secret;
use dialog_effects::storage::{Location, StorageError};
use dialog_effects::{archive, credential, memory};

use std::fmt::Display;

use crate::resource::Resource;

/// Trait for types that can serve as a mounted space provider.
pub trait SpaceProvider:
    Provider<archive::Get>
    + Provider<archive::Put>
    + Provider<memory::Resolve>
    + Provider<memory::Publish>
    + Provider<memory::Retract>
    + Provider<credential::Load<Credential>>
    + Provider<credential::Save<Credential>>
    + Provider<credential::Load<Secret>>
    + Provider<credential::Save<Secret>>
    + ConditionalSend
    + ConditionalSync
    + Clone
    + 'static
{
}

impl<T> SpaceProvider for T where
    T: Provider<archive::Get>
        + Provider<archive::Put>
        + Provider<memory::Resolve>
        + Provider<memory::Publish>
        + Provider<memory::Retract>
        + Provider<credential::Load<Credential>>
        + Provider<credential::Save<Credential>>
        + Provider<credential::Load<Secret>>
        + Provider<credential::Save<Secret>>
        + ConditionalSend
        + ConditionalSync
        + Clone
        + 'static
{
}

/// A composed set of providers for a single mounted space.
#[derive(Clone, dialog_capability::Provider)]
pub struct Space<A, M, C, D> {
    /// Archive provider.
    #[provide(archive::Get, archive::Put)]
    pub archive: A,

    /// Memory provider.
    #[provide(memory::Resolve, memory::Publish, memory::Retract)]
    pub memory: M,

    /// Credential provider.
    #[provide(
        credential::Load<Credential>,
        credential::Save<Credential>,
        credential::Load<Secret>,
        credential::Save<Secret>
    )]
    pub credential: C,

    /// Certificate provider manual implementation are used because of the
    /// complex generics
    pub certificate: D,
}

#[cfg_attr(not(target_arch = "wasm32"), async_trait::async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait::async_trait(?Send))]
impl<Archive, Memory, Credential, Certificate, P> Provider<Prove<P>>
    for Space<Archive, Memory, Credential, Certificate>
where
    P: Protocol,
    P::Access: Clone + ConditionalSend + ConditionalSync,
    P::Certificate: Clone + ConditionalSend + ConditionalSync,
    P::Proof: ConditionalSend,
    Certificate: Provider<Prove<P>> + ConditionalSend + ConditionalSync,
    Archive: ConditionalSend + ConditionalSync,
    Memory: ConditionalSend + ConditionalSync,
    Credential: ConditionalSend + ConditionalSync,
{
    async fn execute(&self, input: Capability<Prove<P>>) -> Result<P::Proof, AuthorizeError> {
        input.perform(&self.certificate).await
    }
}

#[cfg_attr(not(target_arch = "wasm32"), async_trait::async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait::async_trait(?Send))]
impl<Archive, Memory, Credential, Certificate, P> Provider<AccessRetain<P>>
    for Space<Archive, Memory, Credential, Certificate>
where
    P: Protocol,
    P::Delegation: ConditionalSend + ConditionalSync,
    Certificate: Provider<AccessRetain<P>> + ConditionalSend + ConditionalSync,
    Archive: ConditionalSend + ConditionalSync,
    Memory: ConditionalSend + ConditionalSync,
    Credential: ConditionalSend + ConditionalSync,
{
    async fn execute(&self, input: Capability<AccessRetain<P>>) -> Result<(), AuthorizeError> {
        input.perform(&self.certificate).await
    }
}

/// Resource<Location> for Space: each field opens from the same Location.
#[cfg_attr(not(target_arch = "wasm32"), async_trait::async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait::async_trait(?Send))]
impl<A, M, C, P> Resource<Location> for Space<A, M, C, P>
where
    A: Resource<Location> + ConditionalSend,
    M: Resource<Location> + ConditionalSend,
    C: Resource<Location> + ConditionalSend,
    P: Resource<Location> + ConditionalSend,
    A::Error: Display,
    M::Error: Display,
    C::Error: Display,
    P::Error: Display,
{
    type Error = StorageError;

    async fn open(location: &Location) -> Result<Self, StorageError> {
        Ok(Space {
            archive: A::open(location)
                .await
                .map_err(|e| StorageError::Storage(e.to_string()))?,
            memory: M::open(location)
                .await
                .map_err(|e| StorageError::Storage(e.to_string()))?,
            credential: C::open(location)
                .await
                .map_err(|e| StorageError::Storage(e.to_string()))?,
            certificate: P::open(location)
                .await
                .map_err(|e| StorageError::Storage(e.to_string()))?,
        })
    }
}
