mod descriptor;
mod the;

pub use descriptor::*;
pub use the::*;

pub use crate::artifact::{
    Attribute as ArtifactsAttribute, Cause, DialogArtifactsError, Entity, Value,
};
pub use crate::concept::with::{With, WithQuery, WithTerms};
pub use crate::relation::descriptor::RelationDescriptor;
pub use crate::schema::Cardinality;
pub use crate::types::{IntoType, Scalar, Type};
pub use crate::{Premise, Term, The};

/// A typed attribute definition generated by `#[derive(Attribute)]`.
///
/// Each attribute newtype (e.g. `struct Name(String)`) implements this
/// trait, which provides:
/// - The scalar Rust type of the attribute's values (`Type`).
/// - Query, conclusion, and term associated types used by the concept system.
/// - Conversion methods between the attribute, its underlying value, and
///   the storage-level [`ArtifactsAttribute`] / [`AttributeDescriptor`].
///
/// Attributes are the atomic building blocks of concepts: a concept is
/// a set of attributes that together describe an entity type.
pub trait Attribute: Sized {
    /// The Rust scalar type of this attribute's values.
    type Type: Scalar;

    /// The query pattern type used when querying this attribute in a concept.
    type Query;
    /// The concrete conclusion type when this attribute is part of a concept result.
    type Conclusion;
    /// The term type used when building query patterns for this attribute.
    type Term;

    /// Returns a reference to the inner value.
    fn value(&self) -> &Self::Type;

    /// Construct an attribute from its inner value
    fn new(value: Self::Type) -> Self;

    /// Returns the attribute descriptor.
    fn descriptor() -> AttributeDescriptor;

    /// Returns the domain as an owned `String`.
    fn domain() -> String {
        Self::descriptor().domain().into()
    }
    /// Returns the attribute name as an owned `String`.
    fn name() -> String {
        Self::descriptor().name().into()
    }

    /// Returns a relation identifier comprised of the attribute's domain and name.
    fn the() -> The {
        Self::descriptor().the().clone()
    }
    /// Returns the description as an owned `String`.
    fn description() -> String {
        Self::descriptor().description().into()
    }
    /// Returns the cardinality of this attribute.
    fn cardinality() -> Cardinality {
        Self::descriptor().cardinality()
    }
    /// Returns the parsed attribute selector (`"domain/name"`).
    fn selector() -> ArtifactsAttribute {
        ArtifactsAttribute::from(Self::descriptor())
    }

    /// Compute blake3 hash of this attribute's schema
    ///
    /// Returns a 32-byte blake3 hash of the CBOR-encoded attribute schema
    /// (domain, name, cardinality, content_type - excluding description)
    fn hash() -> blake3::Hash {
        Self::descriptor().hash()
    }

    /// Format this attribute's hash as a URI
    ///
    /// Returns a string in the format: `the:{blake3_hash_hex}`
    fn to_uri() -> String {
        Self::descriptor().to_uri()
    }

    /// Returns the expected value type, or `None` if any type is accepted.
    fn content_type() -> Option<Type> {
        <Self::Type as IntoType>::TYPE
    }

    /// Start building a query for this attribute on a given entity.
    ///
    /// ```no_run
    /// use dialog_query::attribute::Attribute;
    /// use dialog_query::Term;
    ///
    /// #[derive(dialog_query::Attribute, Clone)]
    /// struct Name(pub String);
    ///
    /// // Query all names for a variable entity
    /// let query = Name::of(Term::var("entity"));
    ///
    /// // Query with a specific value
    /// let query = Name::of(Term::var("entity"))
    ///     .is(Term::from("Alice".to_string()));
    /// ```
    fn of(entity: Term<Entity>) -> AttributeQueryBuilder<Self> {
        AttributeQueryBuilder {
            entity,
            _marker: std::marker::PhantomData,
        }
    }
}

/// Intermediate builder for fluent attribute queries.
///
/// Created by [`Attribute::of`]. Call [`.is()`](AttributeQueryBuilder::is)
/// to constrain the value, or convert directly into a [`WithQuery`] to
/// match any value.
pub struct AttributeQueryBuilder<A: Attribute> {
    entity: Term<Entity>,
    _marker: std::marker::PhantomData<A>,
}

impl<A: Attribute> AttributeQueryBuilder<A> {
    /// Constrain the value term and produce a complete query.
    pub fn is(self, value: Term<A::Type>) -> WithQuery<A> {
        WithQuery {
            this: self.entity,
            has: value,
        }
    }
}

impl<A: Attribute> From<AttributeQueryBuilder<A>> for WithQuery<A> {
    fn from(builder: AttributeQueryBuilder<A>) -> Self {
        WithQuery {
            this: builder.entity,
            has: Term::var("has"),
        }
    }
}

impl<A: Attribute> AttributeQueryBuilder<A>
where
    A: Clone + std::fmt::Debug + Send + 'static,
{
    /// Execute the query matching any value for this attribute.
    pub fn perform<S: crate::query::Source>(
        self,
        source: &S,
    ) -> impl crate::query::Output<With<A>> {
        let query: WithQuery<A> = self.into();
        crate::query::Application::perform(query, source)
    }
}

#[cfg(test)]
mod tests {
    use crate::artifact::Type;
    use crate::attribute::{Attribute, AttributeDescriptor, Cardinality};
    use crate::term::Term;
    use crate::the;

    mod person {
        use crate::Cardinality;
        use crate::attribute::{Attribute, AttributeDescriptor, With, WithQuery, WithTerms};
        use crate::the;
        use crate::types::IntoType;

        pub struct Name(pub String);

        impl Attribute for Name {
            type Type = String;
            type Query = WithQuery<Self>;
            type Conclusion = With<Self>;
            type Term = WithTerms<Self>;

            fn descriptor() -> AttributeDescriptor {
                AttributeDescriptor::new(
                    the!("person/name"),
                    "The name of the person",
                    Cardinality::One,
                    <String as IntoType>::TYPE,
                )
            }

            fn value(&self) -> &Self::Type {
                &self.0
            }

            fn new(value: Self::Type) -> Self {
                Self(value)
            }
        }
    }

    #[dialog_common::test]
    fn test_person_name() {
        let _name = person::Name("hello".into());
        // Basic test that Attribute trait is implemented
        assert_eq!(person::Name::descriptor().domain(), "person");
        assert_eq!(person::Name::descriptor().name(), "name");
    }

    // Tests from attribute_derive_test.rs

    mod employee_derive {
        use crate::Attribute;

        /// Name of the employee
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        /// Job title of the employee
        #[derive(Attribute, Clone)]
        pub struct Job(pub String);

        /// Salary of the employee
        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);
    }

    mod person_derive {
        use crate::Attribute;

        /// Name of the person
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        /// Employees managed by this person
        #[derive(Attribute, Clone)]
        #[cardinality(many)]
        pub struct Manages(pub crate::Entity);
    }

    #[dialog_common::test]
    fn test_employee_name_derives_attribute() {
        let name = employee_derive::Name("Alice".to_string());

        assert_eq!(employee_derive::Name::domain(), "employee-derive");
        assert_eq!(employee_derive::Name::name(), "name");
        assert_eq!(employee_derive::Name::description(), "Name of the employee");
        assert_eq!(employee_derive::Name::cardinality(), Cardinality::One);
        assert_eq!(name.value(), "Alice");
        assert_eq!(
            employee_derive::Name::selector().to_string(),
            "employee-derive/name"
        );
    }

    #[dialog_common::test]
    fn test_employee_job_derives_attribute() {
        let job = employee_derive::Job("Engineer".to_string());

        assert_eq!(employee_derive::Job::domain(), "employee-derive");
        assert_eq!(employee_derive::Job::name(), "job");
        assert_eq!(
            employee_derive::Job::description(),
            "Job title of the employee"
        );
        assert_eq!(employee_derive::Job::cardinality(), Cardinality::One);
        assert_eq!(job.value(), "Engineer");
        assert_eq!(
            employee_derive::Job::selector().to_string(),
            "employee-derive/job"
        );
    }

    #[dialog_common::test]
    fn test_employee_salary_derives_attribute() {
        let salary = employee_derive::Salary(100000);

        assert_eq!(employee_derive::Salary::domain(), "employee-derive");
        assert_eq!(employee_derive::Salary::name(), "salary");
        assert_eq!(
            employee_derive::Salary::description(),
            "Salary of the employee"
        );
        assert_eq!(employee_derive::Salary::cardinality(), Cardinality::One);
        assert_eq!(salary.value(), &100000u32);
        assert_eq!(
            employee_derive::Salary::selector().to_string(),
            "employee-derive/salary"
        );
    }

    #[dialog_common::test]
    fn test_person_derive_domain() {
        let name = person_derive::Name("Bob".to_string());

        assert_eq!(person_derive::Name::domain(), "person-derive");
        assert_eq!(person_derive::Name::name(), "name");
        assert_eq!(
            person_derive::Name::selector().to_string(),
            "person-derive/name"
        );
        assert_eq!(name.value(), "Bob");
    }

    #[dialog_common::test]
    fn test_cardinality_many() {
        assert_eq!(person_derive::Manages::cardinality(), Cardinality::Many);
        assert_eq!(
            person_derive::Manages::description(),
            "Employees managed by this person"
        );
        assert_eq!(person_derive::Manages::domain(), "person-derive");
    }

    mod custom_ns_derive {
        use crate::Attribute;

        /// Custom domain override test
        #[derive(Attribute, Clone)]
        #[domain = "custom"]
        pub struct Field(pub String);
    }

    #[dialog_common::test]
    fn test_custom_domain_override_derive() {
        let field = custom_ns_derive::Field("value".to_string());

        assert_eq!(custom_ns_derive::Field::domain(), "custom");
        assert_eq!(custom_ns_derive::Field::name(), "field");
        assert_eq!(
            custom_ns_derive::Field::selector().to_string(),
            "custom/field"
        );
        assert_eq!(field.value(), "value");
    }

    // Tests from attribute_identifier_test.rs

    mod employee_ident {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);

        #[derive(Attribute, Clone)]
        pub struct Job(pub String);
    }

    mod person_ident {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);
    }

    #[dialog_common::test]
    fn test_attribute_hash_stability() {
        let hash1 = employee_ident::Name::hash();
        let hash2 = employee_ident::Name::hash();

        assert_eq!(
            hash1, hash2,
            "Same attribute should produce identical hashes"
        );
    }

    #[dialog_common::test]
    fn test_different_attributes_different_hashes() {
        let name_hash = employee_ident::Name::hash();
        let salary_hash = employee_ident::Salary::hash();
        let job_hash = employee_ident::Job::hash();

        assert_ne!(
            name_hash, salary_hash,
            "Name and Salary should have different hashes"
        );
        assert_ne!(
            name_hash, job_hash,
            "Name and Job should have different hashes"
        );
        assert_ne!(
            salary_hash, job_hash,
            "Salary and Job should have different hashes"
        );
    }

    #[dialog_common::test]
    fn test_same_name_different_domain_different_hashes() {
        let employee_name_hash = employee_ident::Name::hash();
        let person_name_hash = person_ident::Name::hash();

        assert_ne!(
            employee_name_hash, person_name_hash,
            "employee::Name and person::Name should have different hashes"
        );
    }

    #[dialog_common::test]
    fn test_attribute_uri_format() {
        let uri = employee_ident::Name::to_uri();

        assert!(
            uri.starts_with("the:"),
            "URI should start with 'the:' prefix"
        );
        // base58 encoding of 32 bytes is typically 43-44 characters
        assert!(uri.len() > 4, "URI should have content after 'the:' prefix");
    }

    #[dialog_common::test]
    fn test_attribute_uri_roundtrip() {
        let uri = employee_ident::Name::to_uri();
        let parsed_hash = AttributeDescriptor::parse_uri(&uri);

        assert!(parsed_hash.is_some(), "Should be able to parse valid URI");
        assert_eq!(
            parsed_hash.unwrap(),
            employee_ident::Name::hash(),
            "Parsed hash should match original hash"
        );
    }

    #[dialog_common::test]
    fn test_attribute_uri_parse_invalid() {
        assert!(
            AttributeDescriptor::parse_uri("invalid").is_none(),
            "Should fail to parse URI without 'the:' prefix"
        );

        assert!(
            AttributeDescriptor::parse_uri("the:invalid").is_none(),
            "Should fail to parse URI with invalid hash"
        );

        assert!(
            AttributeDescriptor::parse_uri("concept:abcd").is_none(),
            "Should fail to parse URI with wrong prefix"
        );
    }

    #[dialog_common::test]
    fn test_attribute_schema_hash_stability() {
        let schema_hash = employee_ident::Name::descriptor().hash();
        let trait_hash = employee_ident::Name::hash();

        assert_eq!(
            schema_hash, trait_hash,
            "Schema hash and trait hash should match"
        );
    }

    #[dialog_common::test]
    fn test_attribute_cbor_encoding() {
        let cbor1 = employee_ident::Name::descriptor().to_cbor_bytes();
        let cbor2 = employee_ident::Name::descriptor().to_cbor_bytes();

        assert_eq!(cbor1, cbor2, "CBOR encoding should be deterministic");
        assert!(!cbor1.is_empty(), "CBOR encoding should not be empty");
    }

    #[dialog_common::test]
    fn test_attribute_description_does_not_affect_hash() {
        let attr1 = AttributeDescriptor::new(
            the!("user/email"),
            "Primary email address",
            Cardinality::One,
            Some(Type::String),
        );

        let attr2 = AttributeDescriptor::new(
            the!("user/email"),
            "User's email for notifications",
            Cardinality::One,
            Some(Type::String),
        );

        assert_eq!(
            attr1.hash(),
            attr2.hash(),
            "Attributes with different descriptions should have the same hash"
        );

        assert_eq!(
            attr1.to_uri(),
            attr2.to_uri(),
            "Attributes with different descriptions should have the same URI"
        );
    }

    // Tests from attribute_into_term_test.rs

    mod employee_term {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        #[derive(Attribute, Clone)]
        pub struct Job(pub String);

        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);
    }

    #[dialog_common::test]
    fn test_attribute_into_term() {
        let name = employee_term::Name("Alice".into());
        let name_term: Term<String> = name.into();
        assert!(name_term.is_constant());

        let job = employee_term::Job("Engineer".into());
        let job_term: Term<String> = job.into();
        assert!(job_term.is_constant());

        let salary = employee_term::Salary(65000);
        let salary_term: Term<u32> = salary.into();
        assert!(salary_term.is_constant());
    }

    #[dialog_common::test]
    fn test_attribute_from_method() {
        let name = employee_term::Name::from("Alice");
        assert_eq!(name.value(), "Alice");

        let job = employee_term::Job::from("Engineer");
        assert_eq!(job.value(), "Engineer");

        let salary = employee_term::Salary::from(65000u32);
        assert_eq!(*salary.value(), 65000);

        let name_term: Term<String> = employee_term::Name::from("Bob").into();
        assert!(name_term.is_constant());
    }

    #[dialog_common::test]
    fn test_attribute_into_in_match_construction() {
        use crate::{Concept, Entity, Match, Term};

        #[derive(Concept, Debug, Clone)]
        pub struct Employee {
            pub this: Entity,
            pub name: employee_term::Name,
            pub job: employee_term::Job,
            pub salary: employee_term::Salary,
        }

        let pattern = Match::<Employee> {
            this: Term::var("e"),
            name: Term::var("name"),
            salary: Term::var("salary"),
            job: employee_term::Job("Engineer".into()).into(),
        };

        assert!(pattern.job.is_constant());

        let pattern2 = Match::<Employee> {
            this: Term::var("e"),
            name: Term::var("name"),
            salary: Term::var("salary"),
            job: employee_term::Job::from("Engineer").into(),
        };

        assert!(pattern2.job.is_constant());
    }

    // Tests from attribute_domain_test.rs

    mod account_name {
        use crate::Attribute;

        /// Account holder's name
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);
    }

    mod ns_my {
        pub mod config {
            use crate::Attribute;

            /// Configuration key
            #[derive(Attribute, Clone)]
            pub struct Key(pub String);
        }
    }

    #[derive(crate::Attribute, Clone)]
    #[domain("my.custom.namespace")]
    pub struct NsValue(pub String);

    #[derive(crate::Attribute, Clone)]
    #[domain(custom)]
    pub struct NsCustomValue(pub String);

    #[derive(crate::Attribute, Clone)]
    #[domain("io.gozala")]
    pub struct NsDottedValue(pub String);

    mod ns_my_app {
        pub mod user_profile {
            use crate::Attribute;

            /// User email address
            #[derive(Attribute, Clone)]
            pub struct Email(pub String);
        }
    }

    #[dialog_common::test]
    fn test_underscore_to_hyphen_conversion() {
        assert_eq!(account_name::Name::domain(), "account-name");
        assert_eq!(account_name::Name::name(), "name");
        assert_eq!(
            account_name::Name::selector().to_string(),
            "account-name/name"
        );
    }

    #[dialog_common::test]
    fn test_nested_module_domain() {
        assert_eq!(ns_my::config::Key::domain(), "config");
        assert_eq!(ns_my::config::Key::name(), "key");
        assert_eq!(ns_my::config::Key::selector().to_string(), "config/key");
    }

    #[dialog_common::test]
    fn test_explicit_domain_override() {
        assert_eq!(NsValue::domain(), "my.custom.namespace");
        assert_eq!(NsValue::name(), "ns-value");
        assert_eq!(
            NsValue::selector().to_string(),
            "my.custom.namespace/ns-value"
        );
    }

    #[dialog_common::test]
    fn test_domain_identifier_syntax() {
        assert_eq!(NsCustomValue::domain(), "custom");
        assert_eq!(NsCustomValue::name(), "ns-custom-value");
        assert_eq!(
            NsCustomValue::selector().to_string(),
            "custom/ns-custom-value"
        );
    }

    #[dialog_common::test]
    fn test_domain_string_literal_syntax() {
        assert_eq!(NsDottedValue::domain(), "io.gozala");
        assert_eq!(NsDottedValue::name(), "ns-dotted-value");
        assert_eq!(
            NsDottedValue::selector().to_string(),
            "io.gozala/ns-dotted-value"
        );
    }

    #[dialog_common::test]
    fn test_nested_underscore_conversion() {
        assert_eq!(ns_my_app::user_profile::Email::domain(), "user-profile");
        assert_eq!(ns_my_app::user_profile::Email::name(), "email");
        assert_eq!(
            ns_my_app::user_profile::Email::selector().to_string(),
            "user-profile/email"
        );
    }

    #[dialog_common::test]
    fn test_all_metadata_preserved() {
        let name = account_name::Name("John Doe".to_string());

        assert_eq!(account_name::Name::domain(), "account-name");
        assert_eq!(account_name::Name::name(), "name");
        assert_eq!(account_name::Name::description(), "Account holder's name");
        assert_eq!(account_name::Name::cardinality(), Cardinality::One);
        assert_eq!(name.value(), "John Doe");
    }

    // Tests from attribute_naming_test.rs

    mod test_pascal {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct UserName(pub String);

        #[derive(Attribute, Clone)]
        pub struct HTTPRequest(pub String);

        #[derive(Attribute, Clone)]
        pub struct APIKey(pub String);
    }

    #[dialog_common::test]
    fn test_pascal_case_to_kebab_case() {
        assert_eq!(test_pascal::UserName::name(), "user-name");
    }

    #[dialog_common::test]
    fn test_consecutive_capitals() {
        assert_eq!(test_pascal::HTTPRequest::name(), "http-request");
        assert_eq!(test_pascal::APIKey::name(), "api-key");
    }

    #[dialog_common::test]
    fn test_static_values() {
        let ns = test_pascal::UserName::domain();
        let name = test_pascal::UserName::name();
        let desc = test_pascal::UserName::description();

        assert!(!ns.is_empty());
        assert_eq!(name, "user-name");
        let _ = desc;
    }

    #[dialog_common::test]
    fn test_schema_static() {
        let schema = &test_pascal::UserName::descriptor();
        assert_eq!(schema.name(), "user-name");
        assert_eq!(schema.cardinality(), Cardinality::One);
    }
}
