//! Database sessions and query sessions
//!
//! This module provides two main types:
//! - `Session`: For committing changes and rule-aware querying
//! - `QuerySession`: For read-only rule-aware querying

/// Registry for deductive rules, indexed by conclusion entity.
pub mod rule_registry;
/// Transaction system for committing changes.
pub mod transaction;

pub use rule_registry::*;

use crate::EvaluationError;
pub use crate::artifact::{
    Artifact, ArtifactSelector, ArtifactStore, ConditionalSend, ConditionalSync, Constrained,
    DialogArtifactsError,
};
use crate::concept::descriptor::ConceptDescriptor;
use crate::concept::query::ConceptRules;
use crate::error::TransactionError;
use crate::query::Application;
use crate::query::Source;
use crate::rule::When;
use crate::rule::deductive::DeductiveRule as DeductiveRuleImpl;
use crate::session::transaction::Transaction;
use crate::{DeductiveRule, Store};
use transaction::Edit;

/// A read-write database session combining a [`Store`] with a [`RuleRegistry`].
///
/// `Session` is the primary entry point for interacting with the knowledge
/// base. It supports both writes (via [`Transaction`](crate::session::transaction::Transaction)s)
/// and rule-aware reads (by implementing [`Source`](crate::query::Source)).
/// Registered deductive rules are available to all queries run against
/// this session.
///
/// # Examples
///
/// ```no_run
/// # use dialog_query::{Session, Attribute, Entity};
/// #[derive(Attribute, Clone)]
/// #[domain(user)]
/// struct Name(String);
///
/// # async fn example(store: impl dialog_query::Store) -> Result<(), Box<dyn std::error::Error>> {
/// let entity = Entity::new()?;
/// let mut session = Session::open(store);
///
/// // Commit changes using a transaction
/// let mut edit = session.edit();
/// edit.assert(Name::of(entity).is("Alice"));
/// session.commit(edit).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct Session<S: Store> {
    /// The underlying store for database operations
    store: S,
    /// Registry of the rules
    rules: RuleRegistry,
}

impl<S: Store> Session<S> {
    /// Open a new session with the provided store
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::Session;
    /// # fn example(artifacts_store: impl dialog_query::Store) {
    /// let session = Session::open(artifacts_store);
    /// # }
    /// ```
    pub fn open(store: S) -> Self {
        Session {
            store,
            rules: RuleRegistry::new(),
        }
    }

    /// Register a new rule into the session
    pub fn register(mut self, rule: DeductiveRule) -> Result<Self, EvaluationError> {
        self.rules.register(rule)?;
        Ok(self)
    }

    /// Install a rule from a function - concept inferred from function parameter.
    ///
    /// # Example
    ///
    /// ```rs
    /// use dialog_query::{Session, When};
    /// use dialog_query::Query;
    ///
    /// // Given a concept `Person` with Query<Person> generated by derive macro:
    /// fn person_rule(person: Query<Person>) -> impl When {
    ///     (
    ///         Query::<Person> {
    ///             this: person.this,
    ///             name: person.name,
    ///             age: person.age,
    ///         },
    ///     )
    /// }
    ///
    /// let session = session.install(person_rule)?;
    /// ```
    pub fn install<M, W>(self, rule: impl Fn(M) -> W) -> Result<Self, EvaluationError>
    where
        M: Application + Default + Into<ConceptDescriptor>,
        W: When,
    {
        let query = M::default();
        let concept: ConceptDescriptor = query.clone().into();
        let when = rule(query).into_premises();
        let premises = when.into_vec();
        let rule =
            DeductiveRuleImpl::new(concept, premises).map_err(|e| EvaluationError::Planning {
                message: e.to_string(),
            })?;
        self.register(rule)
    }

    /// Create a new transaction for imperative API usage
    ///
    /// Returns a Transaction that can be used to batch operations before committing.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::{Session, Attribute, Entity};
    /// # #[derive(Attribute, Clone)]
    /// # #[domain(user)]
    /// # struct Name(String);
    /// # async fn example(store: impl dialog_query::Store) -> Result<(), Box<dyn std::error::Error>> {
    /// let entity = Entity::new()?;
    /// let mut session = Session::open(store);
    /// let mut transaction = session.edit();
    ///
    /// // Add operations to the transaction
    /// transaction.assert(Name::of(entity).is("Alice"));
    ///
    /// // Commit the transaction
    /// session.commit(transaction).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub fn edit(&self) -> Transaction {
        Transaction::new()
    }

    /// Commit a transaction to the database
    ///
    /// Takes ownership of a Transaction and commits all its operations.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::{Session, Attribute, Entity};
    /// # #[derive(Attribute, Clone)]
    /// # #[domain(user)]
    /// # struct Name(String);
    /// # async fn example(store: impl dialog_query::Store) -> Result<(), Box<dyn std::error::Error>> {
    /// let entity = Entity::new()?;
    /// let mut session = Session::open(store);
    /// let mut edit = session.edit();
    ///
    /// edit.assert(Name::of(entity).is("Alice"));
    /// session.commit(edit).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn commit(&mut self, transaction: Transaction) -> Result<(), TransactionError> {
        self.store.commit(transaction.into_stream()).await?;
        Ok(())
    }

    /// Legacy method - converts claims to instructions directly
    ///
    /// Accepts `Vec<Claim>`, single claims, or `Claims` collections.
    /// This method is kept for backwards compatibility.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::{Session, Attribute, Entity};
    /// # #[derive(Attribute, Clone)]
    /// # #[domain(user)]
    /// # struct Name(String);
    /// # async fn example(store: impl dialog_query::Store) -> Result<(), Box<dyn std::error::Error>> {
    /// let alice = Entity::new()?;
    /// let bob = Entity::new()?;
    /// let mut session = Session::open(store);
    ///
    /// // Can pass any items that implement Edit
    /// session.transact([
    ///     Name::of(alice).is("Alice"),
    ///     Name::of(bob).is("Bob"),
    /// ]).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn transact<E, D>(&mut self, changes: D) -> Result<(), DialogArtifactsError>
    where
        E: Edit,
        D: IntoIterator<Item = E>,
    {
        let mut transaction = self.edit();
        // Go over each change and merge it into the transaction
        for change in changes {
            change.merge(&mut transaction);
        }

        // commit transaction.
        self.store.commit(transaction.into_stream()).await?;
        Ok(())
    }
}

/// A read-only query session that provides rule-aware querying capabilities
///
/// QuerySession is a lighter-weight alternative to Session that focuses purely on querying
/// with rule resolution support. It can be created from any ArtifactStore and provides
/// an explicit way to enable rule-based inference during queries.
///
/// # Examples
///
/// ```no_run
/// # use dialog_query::{QuerySession, DeductiveRule};
/// # use dialog_query::session::ArtifactStore;
/// # fn example(artifacts: impl ArtifactStore + Clone + Send + Sync + 'static, adult_rule: DeductiveRule) {
/// // Convert an artifact store to a query session
/// let query_session: QuerySession<_> = artifacts.into();
///
/// // Install rules for more advanced querying
/// let query_session = query_session.install(adult_rule);
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct QuerySession<S: ArtifactStore> {
    /// The underlying store for read operations
    store: S,
    /// Registry of the rules for inference
    rules: RuleRegistry,
}

impl<S: ArtifactStore> QuerySession<S> {
    /// Create a new query session wrapping the provided store
    ///
    /// The query session starts with no rules and can have rules installed later.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::QuerySession;
    /// # use dialog_query::session::ArtifactStore;
    /// # fn example(artifacts: impl ArtifactStore) {
    /// let query_session = QuerySession::new(artifacts);
    /// # }
    /// ```
    pub fn new(store: S) -> Self {
        Self {
            store,
            rules: RuleRegistry::new(),
        }
    }

    /// Install a deductive rule into the query session
    ///
    /// Rules are indexed by their conclusion operator and can be used during
    /// query evaluation to derive facts that aren't directly stored.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use dialog_query::{QuerySession, DeductiveRule};
    /// # use dialog_query::session::ArtifactStore;
    /// # fn example(artifacts: impl ArtifactStore, adult_rule: DeductiveRule, senior_rule: DeductiveRule) -> Result<(), dialog_query::EvaluationError> {
    /// let query_session = QuerySession::new(artifacts)
    ///     .install(adult_rule)?
    ///     .install(senior_rule)?;
    /// # Ok(())
    /// # }
    /// ```
    pub fn install(mut self, rule: DeductiveRule) -> Result<Self, EvaluationError> {
        self.rules.register(rule)?;
        Ok(self)
    }

    /// Get a reference to the underlying store
    pub fn store(&self) -> &S {
        &self.store
    }
}

/// Create QuerySession from any ArtifactStore
impl<S: ArtifactStore + Clone + Send + Sync + 'static> From<S> for QuerySession<S> {
    fn from(store: S) -> Self {
        Self::new(store)
    }
}

/// Implement Source trait for QuerySession to provide rule resolution capabilities
impl<S: ArtifactStore + Clone + Send + Sync + 'static> Source for QuerySession<S> {
    fn acquire(&self, predicate: &ConceptDescriptor) -> Result<ConceptRules, EvaluationError> {
        self.rules.acquire(predicate)
    }
}

/// Forward ArtifactStore methods to the wrapped store
impl<S: ArtifactStore> ArtifactStore for QuerySession<S> {
    fn select(
        &self,
        artifact_selector: ArtifactSelector<Constrained>,
    ) -> impl futures_core::Stream<Item = Result<Artifact, DialogArtifactsError>>
    + ConditionalSend
    + 'static {
        self.store.select(artifact_selector)
    }
}

/// Implement Source trait for Session to provide rule resolution capabilities
///
/// This implementation allows Session to be used directly with the Query trait
/// while providing access to both stored artifacts and registered rules.
impl<S: Store + ConditionalSend + ConditionalSync + 'static> Source for Session<S> {
    fn acquire(&self, predicate: &ConceptDescriptor) -> Result<ConceptRules, EvaluationError> {
        self.rules.acquire(predicate)
    }
}

/// Forward ArtifactStore methods to the wrapped store
impl<S: Store> ArtifactStore for Session<S> {
    fn select(
        &self,
        artifact_selector: ArtifactSelector<Constrained>,
    ) -> impl futures_core::Stream<Item = Result<Artifact, DialogArtifactsError>>
    + ConditionalSend
    + 'static {
        self.store.select(artifact_selector)
    }
}

#[cfg(test)]
mod tests {
    // Allow the derive macro to reference dialog_query:: from within the crate
    extern crate self as dialog_query;

    use std::collections::{HashMap, HashSet};
    use std::sync::Arc;

    use crate::Match;
    use crate::artifact::{Entity, Value};
    use crate::attribute::query::AttributeQuery;
    use crate::query::Output;
    use crate::session::RuleRegistry;
    use crate::source::Source;
    use crate::the;

    use crate::{
        AttributeDescriptor, Cardinality, Concept, Parameters, Query, Term, Type,
        concept::descriptor::ConceptDescriptor,
    };
    use dialog_artifacts::helpers::{test_operator, test_repo};

    use super::*;

    #[dialog_common::test]
    async fn it_queries_asserted_facts() -> anyhow::Result<()> {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;
        let alice = Entity::new()?;
        let bob = Entity::new()?;
        let mallory = Entity::new()?;

        {
            let mut tx = Transaction::new();
            tx.assert(
                the!("person/name")
                    .of(alice.clone())
                    .is("Alice".to_string()),
            )
            .assert(the!("person/age").of(alice.clone()).is(25u32))
            .assert(the!("person/name").of(bob.clone()).is("Bob".to_string()))
            .assert(the!("person/age").of(bob.clone()).is(30u32))
            .assert(
                the!("person/name")
                    .of(mallory.clone())
                    .is("Mallory".to_string()),
            );
            branch.commit(tx.into_stream()).perform(&operator).await?;
        }
        let session = Source::new(&branch, &operator, RuleRegistry::new());

        let person = ConceptDescriptor::from([
            (
                "name",
                AttributeDescriptor::new(
                    the!("person/name"),
                    "person name",
                    Cardinality::One,
                    Some(Type::String),
                ),
            ),
            (
                "age",
                AttributeDescriptor::new(
                    the!("person/age"),
                    "person age",
                    Cardinality::One,
                    Some(Type::UnsignedInt),
                ),
            ),
        ]);

        let name_param = Term::var("name");
        let age_param = Term::var("age");
        let mut params = Parameters::new();
        params.insert("name".into(), Term::var("name"));
        params.insert("age".into(), Term::var("age"));

        // Use new query API directly on application
        let application = person.apply(params)?;

        let selection = futures_util::TryStreamExt::try_collect::<Vec<_>>(
            application.evaluate(Match::new().seed(), &session),
        )
        .await?;
        assert_eq!(selection.len(), 2); // Should find just Alice and Bob

        // Check that we have both Alice and Bob (order may vary)
        let mut found_alice = false;
        let mut found_bob = false;

        for match_result in selection.iter() {
            let person_name = match_result.lookup(&name_param)?;
            let person_age = match_result.lookup(&age_param)?;

            match person_name {
                Value::String(name_str) if name_str == "Alice" => {
                    assert_eq!(person_age, Value::UnsignedInt(25));
                    found_alice = true;
                }
                Value::String(name_str) if name_str == "Bob" => {
                    assert_eq!(person_age, Value::UnsignedInt(30));
                    found_bob = true;
                }
                _ => panic!("Unexpected person: {:?}", person_name),
            }
        }

        assert!(found_alice, "Should find Alice");
        assert!(found_bob, "Should find Bob");

        Ok(())
    }

    #[dialog_common::test]
    async fn it_plans_concept_with_mixed_parameters() -> anyhow::Result<()> {
        // Set up concept with attributes
        let mut attributes = HashMap::new();
        attributes.insert(
            "name".into(),
            AttributeDescriptor::new(
                the!("person/name"),
                "person name",
                Cardinality::One,
                Some(Type::String),
            ),
        );
        attributes.insert(
            "age".into(),
            AttributeDescriptor::new(
                the!("person/age"),
                "person age",
                Cardinality::One,
                Some(Type::UnsignedInt),
            ),
        );

        let person = ConceptDescriptor::from(attributes);

        // Mixed case - valid parameters with some matching attributes (should succeed)
        let mut mixed_params = Parameters::new();
        mixed_params.insert("name".into(), Term::var("person_name")); // This matches
        mixed_params.insert("age".into(), Term::blank()); // This matches but is blank

        person.apply(mixed_params)?;

        Ok(())
    }

    #[dialog_common::test]
    async fn it_asserts_and_queries_concept() -> anyhow::Result<()> {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;

        let person = ConceptDescriptor::from([
            (
                "name",
                AttributeDescriptor::new(
                    the!("person/name"),
                    "person name",
                    Cardinality::One,
                    Some(Type::String),
                ),
            ),
            (
                "age",
                AttributeDescriptor::new(
                    the!("person/age"),
                    "person age",
                    Cardinality::One,
                    Some(Type::UnsignedInt),
                ),
            ),
        ]);

        let alice = person
            .create()
            .with("name", "Alice".to_string())
            .with("age", 25usize)
            .build()?;

        let bob = person
            .create()
            .with("name", "Bob".to_string())
            .with("age", 30usize)
            .build()?;

        let mut tx = Transaction::new();
        tx.assert(alice);
        tx.assert(bob);
        branch.commit(tx.into_stream()).perform(&operator).await?;
        let session = Source::new(&branch, &operator, RuleRegistry::new());

        let name_param = Term::var("name");
        let age_param = Term::var("age");
        let mut params = Parameters::new();
        params.insert("name".into(), Term::var("name"));
        params.insert("age".into(), Term::var("age"));

        // Let's test with empty parameters first to see the exact error
        let application = person.apply(params)?;

        let selection = futures_util::TryStreamExt::try_collect::<Vec<_>>(
            application.evaluate(Match::new().seed(), &session),
        )
        .await?;
        assert_eq!(selection.len(), 2); // Should find just Alice and Bob

        // Check that we have both Alice and Bob (order may vary)
        let mut found_alice = false;
        let mut found_bob = false;

        for match_result in selection.iter() {
            let person_name = match_result.lookup(&name_param)?;
            let person_age = match_result.lookup(&age_param)?;

            match person_name {
                Value::String(name_str) if name_str == "Alice" => {
                    assert_eq!(person_age, Value::UnsignedInt(25));
                    found_alice = true;
                }
                Value::String(name_str) if name_str == "Bob" => {
                    assert_eq!(person_age, Value::UnsignedInt(30));
                    found_bob = true;
                }
                _ => panic!("Unexpected person: {:?}", person_name),
            }
        }

        assert!(found_alice, "Should find Alice");
        assert!(found_bob, "Should find Bob");

        Ok(())
    }

    #[dialog_common::test]
    async fn it_evaluates_derived_rules() -> anyhow::Result<()> {
        mod employee {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Name(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Job(pub String);
        }

        mod stuff {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Name(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Role(pub String);
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Employee {
            /// Employee
            pub this: Entity,
            /// Employee Name
            pub name: employee::Name,
            /// The job title of the employee
            pub job: employee::Job,
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Stuff {
            pub this: Entity,
            /// Name of the stuff member
            pub name: stuff::Name,
            /// Role of the stuff member
            pub role: stuff::Role,
        }

        // employee can be derived from the stuff concept
        let employee_predicate: ConceptDescriptor = Query::<Employee>::default().into();
        let employee_from_stuff = DeductiveRule::new(
            employee_predicate,
            vec![
                AttributeQuery::new(
                    Term::from(the!("stuff/name")),
                    Term::var("this"),
                    Term::var("name"),
                    Term::blank(),
                    None,
                )
                .into(),
                AttributeQuery::new(
                    Term::from(the!("stuff/role")),
                    Term::var("this"),
                    Term::var("job"),
                    Term::blank(),
                    None,
                )
                .into(),
            ],
        )?;

        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;
        let mut rules = RuleRegistry::new();
        rules.register(employee_from_stuff)?;

        let stuff_predicate: ConceptDescriptor = Query::<Stuff>::default().into();
        let alice = stuff_predicate
            .create()
            .with("name", "Alice".to_string())
            .with("role", "manager".to_string())
            .build()?;

        let bob = stuff_predicate
            .create()
            .with("name", "Bob".to_string())
            .with("role", "developer".to_string())
            .build()?;

        let _mallory = Stuff {
            this: Entity::new()?,
            name: stuff::Name("Mallory".into()),
            role: stuff::Role("developer".into()),
        };

        let mut tx = Transaction::new();
        tx.assert(alice);
        tx.assert(bob);
        branch.commit(tx.into_stream()).perform(&operator).await?;

        let session = Source::new(&branch, &operator, rules);
        let query_stuff = Query::<Stuff> {
            this: Term::var("stuff"),
            name: Term::var("name"),
            role: Term::var("job"),
        };

        let stuff = query_stuff.perform(&session).try_vec().await?;

        assert_eq!(stuff.len(), 2);

        // Now we query for employees and expect that employee_from_stuff
        // rule will provide a translation
        let query_employee = Query::<Employee> {
            this: Term::var("employee"),
            name: Term::var("name"),
            job: Term::var("job"),
        };

        let employees = Output::try_vec(query_employee.perform(&session)).await?;

        assert_eq!(employees.len(), 2);
        println!("{:?}", employees);

        Ok(())
    }

    #[dialog_common::test]
    async fn it_installs_rule_via_api() -> anyhow::Result<()> {
        use crate::rule::When;

        mod employee {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Name(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Job(pub String);
        }

        mod stuff {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Name(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Role(pub String);
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Employee {
            /// Employee
            pub this: Entity,
            /// Employee Name
            pub name: employee::Name,
            /// The job title of the employee
            pub job: employee::Job,
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Stuff {
            pub this: Entity,
            /// Name of the stuff member
            pub name: stuff::Name,
            /// Role of the stuff member
            pub role: stuff::Role,
        }

        // Define a rule using the clean function API - no manual DeductiveRule construction!
        fn employee_from_stuff(employee: Query<Employee>) -> impl When {
            // This rule says: "An employee exists when there's stuff with matching attributes"
            // The premises check for stuff/name and stuff/role matching employee/name and employee/job
            (
                Query::<Stuff> {
                    this: employee.this.clone(),
                    name: employee.name.clone(),
                    role: employee.job,
                },
                AttributeQuery::new(
                    Term::from(the!("stuff/name")),
                    employee.this,
                    employee.name.clone().into(),
                    Term::blank(),
                    None,
                ),
            )
        }

        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;

        // Replicate Session::install logic for RuleRegistry
        let query = Query::<Employee>::default();
        let concept: ConceptDescriptor = query.clone().into();
        let when = employee_from_stuff(query).into_premises();
        let premises = when.into_vec();
        let install_rule =
            DeductiveRule::new(concept, premises).map_err(|e| EvaluationError::Planning {
                message: e.to_string(),
            })?;
        let mut rules = RuleRegistry::new();
        rules.register(install_rule)?;

        // Create test data as Stuff
        let stuff_predicate: ConceptDescriptor = Query::<Stuff>::default().into();
        let alice = stuff_predicate
            .create()
            .with("name", "Alice".to_string())
            .with("role", "manager".to_string())
            .build()?;

        let bob = stuff_predicate
            .create()
            .with("name", "Bob".to_string())
            .with("role", "developer".to_string())
            .build()?;

        let mut tx = Transaction::new();
        tx.assert(alice);
        tx.assert(bob);
        branch.commit(tx.into_stream()).perform(&operator).await?;

        let session = Source::new(&branch, &operator, rules);
        // Verify Stuff records exist
        let query_stuff = Query::<Stuff> {
            this: Term::var("stuff"),
            name: Term::var("name"),
            role: Term::var("job"),
        };

        let stuff = query_stuff.perform(&session).try_vec().await?;
        assert_eq!(stuff.len(), 2, "Should have 2 Stuff records");

        // Query for Employees - the rule should derive them from Stuff
        let query_employee = Query::<Employee> {
            this: Term::var("employee"),
            name: Term::var("name"),
            job: Term::var("job"),
        };

        let employees = Output::try_vec(query_employee.perform(&session)).await?;

        // The rule should have derived 2 Employee instances from the 2 Stuff instances
        assert_eq!(
            employees.len(),
            2,
            "Rule should derive 2 employees from stuff"
        );

        // Verify the derived data is correct
        let mut found_alice = false;
        let mut found_bob = false;

        for employee in employees {
            use crate::Attribute as _;
            match employee.name.value().as_str() {
                "Alice" => {
                    assert_eq!(employee.job.value(), "manager");
                    found_alice = true;
                }
                "Bob" => {
                    assert_eq!(employee.job.value(), "developer");
                    found_bob = true;
                }
                name => panic!("Unexpected employee: {}", name),
            }
        }

        assert!(found_alice, "Should find Alice as an employee");
        assert!(found_bob, "Should find Bob as an employee");

        Ok(())
    }

    #[dialog_common::test]
    async fn it_resolves_rules_via_source_trait() -> anyhow::Result<()> {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let _branch = repo.branch("main").open().perform(&operator).await?;

        let adult_conclusion = ConceptDescriptor::from(vec![
            (
                "name",
                AttributeDescriptor::new(
                    the!("adult/name"),
                    "Adult name",
                    Cardinality::One,
                    Some(Type::String),
                ),
            ),
            (
                "age",
                AttributeDescriptor::new(
                    the!("adult/age"),
                    "Adult age",
                    Cardinality::One,
                    Some(Type::UnsignedInt),
                ),
            ),
        ]);

        let rule = DeductiveRule::from(&adult_conclusion);

        let mut registry = RuleRegistry::new();
        registry.register(rule.clone())?;

        // Verify resolve returns ConceptRules that can plan
        let rules = registry.acquire(&adult_conclusion)?;
        let candidate = Match::new();
        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));
        let _plan = rules.plan(&terms, &candidate);

        Ok(())
    }

    #[dialog_common::test]
    async fn it_accepts_source_trait_implementations() -> anyhow::Result<()> {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;

        let concept = ConceptDescriptor::from([(
            "name",
            AttributeDescriptor::new(
                the!("person/name"),
                "Person name",
                Cardinality::One,
                Some(Type::String),
            ),
        )]);
        let rule = DeductiveRule::from(&concept);

        // Test with RuleRegistry + Source
        let mut registry = RuleRegistry::new();
        registry.register(rule.clone())?;
        let source = Source::new(&branch, &operator, registry);
        let _rules = source.acquire(&concept)?;

        Ok(())
    }

    #[dialog_common::test]
    async fn it_converts_source_explicitly() -> anyhow::Result<()> {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let _branch = repo.branch("main").open().perform(&operator).await?;

        let adult_concept = ConceptDescriptor::from([(
            "name".to_string(),
            AttributeDescriptor::new(
                the!("person/name"),
                "Adult name",
                Cardinality::One,
                Some(Type::String),
            ),
        )]);

        let adult_rule = DeductiveRule::from(&adult_concept);

        let mut registry = RuleRegistry::new();
        registry.register(adult_rule.clone())?;

        // Verify resolve works
        let _rules = registry.acquire(&adult_concept)?;

        Ok(())
    }

    mod implicit_attr_test {
        use crate::Attribute;

        #[derive(Attribute, Clone, PartialEq)]
        pub struct Name(pub String);

        #[derive(Attribute, Clone, PartialEq)]
        pub struct Role(pub String);
    }

    #[dialog_common::test]
    async fn it_filters_with_like_formula_in_rule() -> anyhow::Result<()> {
        use crate::Attribute;
        use crate::formula::Like;
        use crate::rule::When;

        mod note_like_test {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Title(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct MatchedTitle(pub String);
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Note {
            pub this: Entity,
            pub title: note_like_test::Title,
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct MatchingNote {
            pub this: Entity,
            pub title: note_like_test::MatchedTitle,
        }

        // Rule: a MatchingNote is a Note whose title matches "Hello*"
        fn matching_notes(result: Query<MatchingNote>) -> impl When {
            let title = Term::<String>::var("_title");
            (
                Query::<Note> {
                    this: result.this,
                    title: title.clone(),
                },
                Query::<Like> {
                    text: title,
                    pattern: Term::from("Hello*".to_string()),
                    is: result.title,
                },
            )
        }

        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;
        let query_m = Query::<MatchingNote>::default();
        let concept_m: ConceptDescriptor = query_m.clone().into();
        let when_m = matching_notes(query_m).into_premises();
        let rule_m = DeductiveRule::new(concept_m, when_m.into_vec()).map_err(|e| {
            EvaluationError::Planning {
                message: e.to_string(),
            }
        })?;
        let mut rules = RuleRegistry::new();
        rules.register(rule_m)?;

        let mut transaction = Transaction::new();
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_like_test::Title("Hello World".into()),
        });
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_like_test::Title("Hello Rust".into()),
        });
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_like_test::Title("Goodbye World".into()),
        });
        branch
            .commit(transaction.into_stream())
            .perform(&operator)
            .await?;

        let session = Source::new(&branch, &operator, rules);
        let results = Query::<MatchingNote> {
            this: Term::var("note"),
            title: Term::var("title"),
        }
        .perform(&session)
        .try_vec()
        .await?;

        assert_eq!(results.len(), 2, "Should match only the two Hello* notes");

        let mut titles: Vec<String> = results.iter().map(|n| n.title.value().clone()).collect();
        titles.sort();
        assert_eq!(titles, vec!["Hello Rust", "Hello World"]);

        Ok(())
    }

    #[dialog_common::test]
    async fn it_negates_like_formula_in_rule() -> anyhow::Result<()> {
        use crate::Attribute;
        use crate::formula::Like;
        use crate::rule::When;

        mod note_not_like_test {
            use crate::Attribute;

            #[derive(Attribute, Clone, PartialEq)]
            pub struct Title(pub String);

            #[derive(Attribute, Clone, PartialEq)]
            pub struct FilteredTitle(pub String);
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Note {
            pub this: Entity,
            pub title: note_not_like_test::Title,
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct NonDraftNote {
            pub this: Entity,
            pub title: note_not_like_test::FilteredTitle,
        }

        // Rule: a NonDraftNote is a Note whose title does NOT match "Draft:*"
        fn non_draft_notes(result: Query<NonDraftNote>) -> impl When {
            let title = Term::<String>::var("_title");
            (
                Query::<Note> {
                    this: result.this,
                    title: title.clone(),
                },
                Query::<Like> {
                    text: title.clone(),
                    pattern: Term::from("*".to_string()),
                    is: result.title,
                },
                !Query::<Like> {
                    text: title,
                    pattern: Term::from("Draft:*".to_string()),
                    is: Term::blank(),
                },
            )
        }

        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;
        let query_n = Query::<NonDraftNote>::default();
        let concept_n: ConceptDescriptor = query_n.clone().into();
        let when_n = non_draft_notes(query_n).into_premises();
        let rule_n = DeductiveRule::new(concept_n, when_n.into_vec()).map_err(|e| {
            EvaluationError::Planning {
                message: e.to_string(),
            }
        })?;
        let mut rules = RuleRegistry::new();
        rules.register(rule_n)?;

        let mut transaction = Transaction::new();
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_not_like_test::Title("Draft: My Ideas".into()),
        });
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_not_like_test::Title("Published Article".into()),
        });
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_not_like_test::Title("Draft: TODO".into()),
        });
        transaction.assert(Note {
            this: Entity::new()?,
            title: note_not_like_test::Title("Final Report".into()),
        });
        branch
            .commit(transaction.into_stream())
            .perform(&operator)
            .await?;

        let session = Source::new(&branch, &operator, rules);
        let results = Query::<NonDraftNote> {
            this: Term::var("note"),
            title: Term::var("title"),
        }
        .perform(&session)
        .try_vec()
        .await?;

        assert_eq!(results.len(), 2, "Should exclude the two Draft:* notes");

        let mut titles: Vec<String> = results.iter().map(|n| n.title.value().clone()).collect();
        titles.sort();
        assert_eq!(titles, vec!["Final Report", "Published Article"]);

        Ok(())
    }

    #[dialog_common::test]
    async fn it_infers_implicit_attributes() -> anyhow::Result<()> {
        use crate::Attribute as _;
        use crate::rule::When;
        use implicit_attr_test::{Name, Role};

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct Employee {
            /// Employee
            pub this: Entity,
            /// Employee Name
            pub name: Name,
            /// The job title of the employee
            pub role: Role,
        }

        #[derive(Clone, Debug, PartialEq, Concept)]
        pub struct EmployeeWithoutRole {
            /// Employee
            pub this: Entity,
            /// Employee Name
            pub name: Name,
        }

        // Define a rule using the clean function API - no manual DeductiveRule construction!
        fn employee_with_implicit_title(employee: Query<Employee>) -> impl When {
            // This rule says: "An employee exists when there's stuff with matching attributes"
            // The premises check for stuff/name and stuff/role matching employee/name and employee/job
            (
                employee.role.is(Role("employee".into())),
                // employee has a name
                AttributeQuery::new(
                    Term::from(the!("implicit-attr-test/name")),
                    employee.this.clone(),
                    employee.name.clone().into(),
                    Term::blank(),
                    None,
                ),
                // but does not have role (using ! operator)
                !AttributeQuery::new(
                    Term::from(the!("implicit-attr-test/role")),
                    employee.this.clone(),
                    Term::blank(),
                    Term::blank(),
                    None,
                ),
            )
        }

        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;

        // Install the rule using the clean API - no turbofish needed!
        // The type inference works: Employee is inferred from the function parameter
        let query_e = Query::<Employee>::default();
        let concept_e: ConceptDescriptor = query_e.clone().into();
        let when_e = employee_with_implicit_title(query_e).into_premises();
        let rule_e = DeductiveRule::new(concept_e, when_e.into_vec()).map_err(|e| {
            EvaluationError::Planning {
                message: e.to_string(),
            }
        })?;
        let mut rules = RuleRegistry::new();
        rules.register(rule_e)?;

        let mut transaction = Transaction::new();
        transaction.assert(Employee {
            this: Entity::new()?,
            name: Name("Alice".into()),
            role: Role("manager".into()),
        });
        transaction.assert(EmployeeWithoutRole {
            this: Entity::new()?,
            name: Name("Bob".into()),
        });

        // Create test data as Stuff
        branch
            .commit(transaction.into_stream())
            .perform(&operator)
            .await?;

        let session = Source::new(&branch, &operator, rules);
        // Verify Stuff records exist
        let employees = Query::<Employee> {
            this: Term::var("employee"),
            name: Term::var("name"),
            role: Term::var("title"),
        };

        let result = employees.perform(&session).try_vec().await?;
        assert_eq!(result.len(), 2, "Should have 2 Stuff records");

        // Verify the derived data is correct
        let mut found_alice = false;
        let mut found_bob = false;

        for employee in result {
            match employee.name.value().as_str() {
                "Alice" => {
                    assert_eq!(employee.role.value(), "manager");
                    found_alice = true;
                }
                "Bob" => {
                    assert_eq!(employee.role.value(), "employee");
                    found_bob = true;
                }
                name => panic!("Unexpected employee: {}", name),
            }
        }

        assert!(found_alice, "Should find Alice as an employee");
        assert!(found_bob, "Should find Bob as an employee");

        Ok(())
    }

    // Plan caching tests
    //
    // These tests verify that the adornment-keyed plan cache (inspired by magic
    // set optimization) correctly caches, reuses, and invalidates execution plans.

    /// Helper: build a person concept predicate with name and age attributes.
    fn person_concept() -> ConceptDescriptor {
        ConceptDescriptor::from([
            (
                "name",
                AttributeDescriptor::new(
                    the!("person/name"),
                    "",
                    Cardinality::One,
                    Some(Type::String),
                ),
            ),
            (
                "age",
                AttributeDescriptor::new(
                    the!("person/age"),
                    "",
                    Cardinality::One,
                    Some(Type::UnsignedInt),
                ),
            ),
        ])
    }

    #[dialog_common::test]
    fn it_caches_plans_by_adornment() {
        let person = person_concept();
        let rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        let candidate = Match::new();
        let plan1 = rules.plan(&terms, &candidate);
        let plan2 = rules.plan(&terms, &candidate);

        assert!(
            Arc::ptr_eq(&plan1, &plan2),
            "Same adornment should return the same Arc (cache hit)"
        );
    }

    #[dialog_common::test]
    fn it_caches_different_plans_per_adornment() {
        let person = person_concept();
        let rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        let free = Match::new();
        let plan_free = rules.plan(&terms, &free);

        let mut bound = Match::new();
        bound
            .bind(&Term::var("e"), Value::from(Entity::new().unwrap()))
            .unwrap();
        let plan_bound = rules.plan(&terms, &bound);

        assert!(
            !Arc::ptr_eq(&plan_free, &plan_bound),
            "Different adornments should produce distinct cached plans"
        );
    }

    #[dialog_common::test]
    fn it_invalidates_cache_on_rule_install() {
        let person = person_concept();
        let mut rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        // Warm the cache
        let candidate = Match::new();
        let plan_before = rules.plan(&terms, &candidate);

        // Install a rule for the same concept
        let rule = DeductiveRule::from(&person);
        rules.install(rule);

        // Cache should be invalidated — new plan must be computed
        let plan_after = rules.plan(&terms, &candidate);

        assert!(
            !Arc::ptr_eq(&plan_before, &plan_after),
            "Plan should be recomputed after installing a new rule"
        );
    }

    #[dialog_common::test]
    fn it_preserves_cache_for_unrelated_rules() {
        let person = person_concept();
        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        let mut registry = RuleRegistry::new();

        // Warm the cache for the person concept via resolve
        let candidate = Match::new();
        let person_rules = registry.acquire(&person).unwrap();
        let plan_before = person_rules.plan(&terms, &candidate);

        // Install a rule for a DIFFERENT concept entity
        let unrelated = ConceptDescriptor::from([(
            "title",
            AttributeDescriptor::new(the!("book/title"), "", Cardinality::One, Some(Type::String)),
        )]);
        let rule = DeductiveRule::from(&unrelated);
        registry.register(rule).unwrap();

        // Person's cache should be untouched (same ConceptRules, shared Arc)
        let plan_after = person_rules.plan(&terms, &candidate);

        assert!(
            Arc::ptr_eq(&plan_before, &plan_after),
            "Unrelated rule install should not invalidate person's cached plan"
        );
    }

    #[dialog_common::test]
    fn it_preserves_cache_for_duplicate_rules() {
        let person = person_concept();
        let mut rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        // Install a rule and warm the cache
        let rule = DeductiveRule::from(&person);
        rules.install(rule.clone());
        let candidate = Match::new();
        let plan_before = rules.plan(&terms, &candidate);

        // Re-install the exact same rule (duplicate)
        rules.install(rule);

        // Cache should NOT be invalidated — the rule was already present
        let plan_after = rules.plan(&terms, &candidate);

        assert!(
            Arc::ptr_eq(&plan_before, &plan_after),
            "Duplicate rule registration should not invalidate the cache"
        );
    }

    #[dialog_common::test]
    fn it_shares_cache_across_clones() {
        let person = person_concept();
        let rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        // Warm cache on the original
        let candidate = Match::new();
        let plan_original = rules.plan(&terms, &candidate);

        // Clone the ConceptRules — the cache is shared via Arc
        let cloned = rules.clone();
        let plan_cloned = cloned.plan(&terms, &candidate);

        assert!(
            Arc::ptr_eq(&plan_original, &plan_cloned),
            "Cloned ConceptRules should share the plan cache"
        );
    }

    #[dialog_common::test]
    fn it_produces_cheaper_plan_with_bound_entity() {
        use crate::concept::query::adornment::Adornment;

        let person = person_concept();
        let rules = ConceptRules::new(&person);

        let mut terms = Parameters::new();
        terms.insert("this".into(), Term::var("e"));
        terms.insert("name".into(), Term::var("n"));
        terms.insert("age".into(), Term::var("a"));

        let free = Match::new();
        let adornment_free = Adornment::derive(&terms, &free);
        let env_free = adornment_free.into_environment(&terms);
        let free_plan = rules.plan(&terms, &free);

        let mut bound = Match::new();
        bound
            .bind(&Term::var("e"), Value::from(Entity::new().unwrap()))
            .unwrap();
        let adornment_bound = Adornment::derive(&terms, &bound);
        let env_bound = adornment_bound.into_environment(&terms);
        let bound_plan = rules.plan(&terms, &bound);

        // The entity-bound environment should contain "e"
        assert!(
            env_bound.contains("e"),
            "Bound adornment should include entity variable in environment"
        );
        assert!(
            !env_free.contains("e"),
            "Free adornment should not include entity variable in environment"
        );

        // Verify the plans are structurally different
        assert_ne!(
            free_plan, bound_plan,
            "Bound-entity plan should differ from all-free plan"
        );
    }

    #[dialog_common::test]
    async fn it_produces_correct_results_from_cached_plan() -> anyhow::Result<()> {
        // End-to-end test: verify that evaluating a concept with the plan cache
        // produces the same correct results as the pre-cache implementation.
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;
        let alice = Entity::new()?;
        let bob = Entity::new()?;

        {
            let mut tx = Transaction::new();
            tx.assert(
                the!("person/name")
                    .of(alice.clone())
                    .is("Alice".to_string()),
            )
            .assert(the!("person/age").of(alice.clone()).is(30u32))
            .assert(the!("person/name").of(bob.clone()).is("Bob".to_string()))
            .assert(the!("person/age").of(bob.clone()).is(25u32));
            branch.commit(tx.into_stream()).perform(&operator).await?;
        }

        let session = Source::new(&branch, &operator, RuleRegistry::new());
        let person = person_concept();
        let name_param = Term::var("name");
        let mut params = Parameters::new();
        params.insert("name".into(), Term::var("name"));
        params.insert("age".into(), Term::var("age"));

        let application = person.apply(params)?;

        // First query -- plan is computed and cached
        let results1: Vec<_> = futures_util::TryStreamExt::try_collect(
            application.clone().evaluate(Match::new().seed(), &session),
        )
        .await?;

        // Second query -- plan is reused from cache
        let results2: Vec<_> = futures_util::TryStreamExt::try_collect(
            application.evaluate(Match::new().seed(), &session),
        )
        .await?;

        assert_eq!(results1.len(), 2, "First query should find 2 people");
        assert_eq!(results2.len(), 2, "Cached query should find 2 people");

        // Both runs should produce the same names
        let names1: HashSet<_> = results1
            .iter()
            .map(|r| r.lookup(&name_param).unwrap())
            .collect();
        let names2: HashSet<_> = results2
            .iter()
            .map(|r| r.lookup(&name_param).unwrap())
            .collect();

        assert_eq!(
            names1, names2,
            "Cached plan should produce identical results"
        );

        Ok(())
    }

    #[dialog_common::test]
    async fn it_produces_correct_results_from_cached_plan_with_bound_entity() -> anyhow::Result<()>
    {
        let operator = test_operator().await;
        let repo = test_repo(&operator).await;
        let branch = repo.branch("main").open().perform(&operator).await?;

        let alice = Entity::new()?;
        let bob = Entity::new()?;

        {
            let mut tx = Transaction::new();
            tx.assert(
                the!("person/name")
                    .of(alice.clone())
                    .is("Alice".to_string()),
            )
            .assert(the!("person/age").of(alice.clone()).is(30u32))
            .assert(the!("person/name").of(bob.clone()).is("Bob".to_string()))
            .assert(the!("person/age").of(bob.clone()).is(25u32));
            branch.commit(tx.into_stream()).perform(&operator).await?;
        }

        let session = Source::new(&branch, &operator, RuleRegistry::new());
        let person = person_concept();

        let name_param = Term::var("name");
        let age_param = Term::var("age");
        let entity_param = Term::var("this");

        let mut params = Parameters::new();
        params.insert("this".into(), Term::var("this"));
        params.insert("name".into(), Term::var("name"));
        params.insert("age".into(), Term::var("age"));

        let application = person.apply(params)?;

        let mut candidate = Match::new();
        candidate.bind(&entity_param, Value::from(alice.clone()))?;

        let results = application
            .evaluate(candidate.seed(), &session)
            .try_vec()
            .await?;

        assert_eq!(results.len(), 1, "Should find exactly one person (Alice)");
        assert_eq!(
            results[0].lookup(&name_param)?,
            Value::String("Alice".into()),
            "Should resolve to Alice"
        );
        assert_eq!(
            results[0].lookup(&age_param)?,
            Value::UnsignedInt(30),
            "Should have Alice's age"
        );

        Ok(())
    }
}
