[package]
name = "x-query"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
x-common = { workspace = true }

async-stream = { workspace = true }
async-trait = { workspace = true }
base58 = { workspace = true }
blake3 = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
ulid = { workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
# tokio = { workspace = true, features = ["macros", "rt"] }
wasm-bindgen-test = { workspace = true }
