[package]
name = "x-storage"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
x-common = { workspace = true }

async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
base58 = { workspace = true }
tokio = { workspace = true, features = ["sync", "fs"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = { workspace = true }
rexie = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt", "fs"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
wasm-bindgen-test = { workspace = true }
