on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      # Run CI for brannches with this prefix so that radicle integration
      # can pick those CI jobs and report them in patches (equivalent of pull
      # requests)
      - patches/*

name: 'Test'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_nix:
    name: 'Lint Nix'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          send-statistics: false
          ignore-missing-flake-lock: false

  lint_rust:
    name: 'Lint Rust'
    needs: ['lint_nix']
    runs-on: 'ubuntu-latest'
    steps:
      - uses: cisagov/action-disable-apparmor@v1
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          root-safe-haven: '8096'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: tonk-ops
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: 'Run lints'
        shell: bash
        run: |
          nix develop --accept-flake-config --command lint

  lints:
    name: 'Lints'
    needs: ['lint_nix', 'lint_rust']
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo "Lints are good!"

  tests:
    name: 'Tests'
    needs: ['lints']
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        configuration:
          - 'test:native:debug'
          - 'test:native:release'
          - 'test:web:debug'
          - 'test:web:release'
          - 'test:web:ucan'
          - 'test:cross:integration'
          # FIXME: Currently, NPM package tests run / pass locally, but
          # in CI the test runner is picking up the wrong `chromium` binary
          # The problem is subtle: it finds the correct Nix path, but it
          # chooses the `chromium-browser` binary when it should be choosing
          # the `chromium` binary, and attempts to override this choice
          # through environment variables have proved fruitless. Noting
          # that this worked before because NPM tests were run in a special
          # job where we kept the Chrome that is installed in the Github
          # Runner by default, which "just worked."
          # - 'test:npm'
    steps:
      # NOTE: AppArmor became more restrictive in Ubuntu 24.04 and
      # causes problems for Puppeteer when launching Chrome; it should
      # be safe to disable it.
      # SEE: https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924
      # SEE: https://github.com/actions/runner-images/issues/10015
      - uses: cisagov/action-disable-apparmor@v1
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          root-safe-haven: '8096'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: tonk-ops
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: 'Run test configuration'
        run: |
          nix develop \
            --accept-flake-config \
            --set-env-var TMPDIR $RUNNER_TEMP \
            --command ${{ matrix.configuration }}

